const Categories = [
    {name: 'Celulares', value: 'CELULAR'},
    {name: 'Notebooks', value: 'NOTEBOOK'},
    {name: 'Tablets', value: 'TABLET'},
    {name: 'Informática', value: 'INFORMATICA'},
    {name: 'Acessórios', value: 'ACESSORIO'},
    {name: 'Outros', value: 'OUTRO'},
    {name: 'Assistência', value: 'ASSISTENCIA'},
    {name: 'Receptores', value: 'RECEPTOR'},
    {name: 'Caixas de Som', value: 'CAIXA DE SOM'},
    {name: 'Teclados', value: 'TECLADO'},
    {name: 'Fones de Ouvido', value: 'FONE DE OUVIDO'},
    {name: 'Televisores', value: 'TELEVISOR'},
    {name: 'Roteadores', value: 'ROTEADOR'},
    {name: 'Repetidores', value: 'REPETIDOR'},
    {name: 'Suportes', value: 'SUPORTE'},
    {name: 'Amplificadores', value: 'AMPLIFICADOR'},
    {name: 'Tabacaria', value: 'TABACARIA'},
    {name: 'Carregadores', value: 'CARREGADOR'},
    {name: 'Alto Falantes', value: 'ALTO FALANTE'},
    {name: 'Smartwatches', value: 'SMARTWATCHES'},
    {name: 'Drones', value: 'DRONE'},
    {name: 'Óculos VR', value: 'ÓCULOS VR'},
    {name: 'Câmera de Segurança', value: 'CÂMERA DE SEGURANCA'},
    {name: 'Câmera Digital', value: 'CÂMERA DIGITAL'},
    {name: 'Perfumes', value: 'Perfumes'},
    {name: 'Games', value: 'GAMES'},
    {name: 'Perfumes Árabes', value: 'PERFUMES ÁRABES'},
    {name: 'Som Automotivo', value: 'SOM AUTOMOTIVO'}
  ]

export default Categories
